export const langs = [
  "Abkhaz - аҧсуа",
  "Afar - Afaraf",
  "Afrikaans - Afrikaans",
  "Akan - Akan",
  "Albanian - Shqip",
  "Amharic - አማርኛ",
  "Arabic - العربية",
  "Aragonese - Aragonés",
  "Armenian - Հայերեն",
  "Assamese - অসমীয়া",
  "Avaric - авар мацӀ, магӀарул мацӀ",
  "Avestan - avesta",
  "Aymara - aymar aru",
  "Azerbaijani - azərbaycan dili",
  "Bambara - bamanankan",
  "Bashkir - башҡорт теле",
  "Basque - euskara, euskera",
  "Belarusian - Беларуская",
  "Bengali - বাংলা",
  "Bihari - भोजपुरी",
  "Bislama - Bislama",
  "Bosnian - bosanski jezik",
  "Breton - brezhoneg",
  "Bulgarian - български език",
  "Burmese - ဗမာစာ",
  "Catalan; Valencian - Català",
  "Chamorro - Chamoru",
  "Chechen - нохчийн мотт",
  "Chichewa; Chewa; Nyanja - chiCheŵa, chinyanja",
  "Chinese - 中文 (Zhōngwén), 汉语, 漢語",
  "Chuvash - чӑваш чӗлхи",
  "Cornish - Kernewek",
  "Corsican - corsu, lingua corsa",
  "Cree - ᓀᐦᐃᔭᐍᐏᐣ",
  "Croatian - hrvatski",
  "Czech - česky, čeština",
  "Danish - dansk",
  "Divehi; Dhivehi; Maldivian; - ދިވެހި",
  "Dutch - Nederlands, Vlaams",
  "English - English",
  "Esperanto - Esperanto",
  "Estonian - eesti, eesti keel",
  "Ewe - Eʋegbe",
  "Faroese - føroyskt",
  "Fijian - vosa Vakaviti",
  "Finnish - suomi, suomen kieli",
  "French - français, langue française",
  "Fula; Fulah; Pulaar; Pular - Fulfulde, Pulaar, Pular",
  "Galician - Galego",
  "Georgian - ქართული",
  "German - Deutsch",
  "Greek, Modern - Ελληνικά",
  "Guaraní - Avañeẽ",
  "Gujarati - ગુજરાતી",
  "Haitian; Haitian Creole - Kreyòl ayisyen",
  "Hausa - Hausa, هَوُسَ",
  "Hebrew (modern) - עברית",
  "Herero - Otjiherero",
  "Hindi - हिन्दी, हिंदी",
  "Hiri Motu - Hiri Motu",
  "Hungarian - Magyar",
  "Interlingua - Interlingua",
  "Indonesian - Bahasa Indonesia",
  "Interlingue - Originally called Occidental; then Interlingue after WWII",
  "Irish - Gaeilge",
  "Igbo - Asụsụ Igbo",
  "Inupiaq - Iñupiaq, Iñupiatun",
  "Ido - Ido",
  "Icelandic - Íslenska",
  "Italian - Italiano",
  "Inuktitut - ᐃᓄᒃᑎᑐᑦ",
  "Japanese - 日本語",
  "Javanese - basa Jawa",
  "Kalaallisut, Greenlandic - kalaallisut, kalaallit oqaasii",
  "Kannada - ಕನ್ನಡ",
  "Kanuri - Kanuri",
  "Kashmiri - कश्मीरी, كشميري‎",
  "Kazakh - Қазақ тілі",
  "Khmer - ភាសាខ្មែរ",
  "Kikuyu, Gikuyu - Gĩkũyũ",
  "Kinyarwanda - Ikinyarwanda",
  "Kirghiz, Kyrgyz - кыргыз тили",
  "Komi - коми кыв",
  "Kongo - KiKongo",
  "Korean - 한국어 (韓國語), 조선말 (朝鮮語)",
  "Kurdish - Kurdî, كوردی‎",
  "Kwanyama, Kuanyama - Kuanyama",
  "Latin - latine, lingua latina",
  "Luxembourgish, Letzeburgesch - Lëtzebuergesch",
  "Luganda - Luganda",
  "Limburgish, Limburgan, Limburger - Limburgs",
  "Lingala - Lingála",
  "Lao - ພາສາລາວ",
  "Lithuanian - lietuvių kalba",
  "Luba-Katanga - ",
  "Latvian - latviešu valoda",
  "Manx - Gaelg, Gailck",
  "Macedonian - македонски јазик",
  "Malagasy - Malagasy fiteny",
  "Malay - bahasa Melayu, بهاس ملايو‎",
  "Malayalam - മലയാളം",
  "Maltese - Malti",
  "Māori - te reo Māori",
  "Marathi (Marāṭhī) - मराठी",
  "Marshallese - Kajin M̧ajeļ",
  "Mongolian - монгол",
  "Nauru - Ekakairũ Naoero",
  "Navajo, Navaho - Diné bizaad, Dinékʼehǰí",
  "Norwegian Bokmål - Norsk bokmål",
  "North Ndebele - isiNdebele",
  "Nepali - नेपाली",
  "Ndonga - Owambo",
  "Norwegian Nynorsk - Norsk nynorsk",
  "Norwegian - Norsk",
  "Nuosu - ꆈꌠ꒿ Nuosuhxop",
  "South Ndebele - isiNdebele",
  "Occitan - Occitan",
  "Ojibwe, Ojibwa - ᐊᓂᔑᓈᐯᒧᐎᓐ",
  "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic - ѩзыкъ словѣньскъ",
  "Oromo - Afaan Oromoo",
  "Oriya - ଓଡ଼ିଆ",
  "Ossetian, Ossetic - ирон æвзаг",
  "Panjabi, Punjabi - ਪੰਜਾਬੀ, پنجابی‎",
  "Pāli - पाऴि",
  "Persian - فارسی",
  "Polish - polski",
  "Pashto, Pushto - پښتو",
  "Portuguese - Português",
  "Quechua - Runa Simi, Kichwa",
  "Romansh - rumantsch grischun",
  "Kirundi - kiRundi",
  "Romanian, Moldavian, Moldovan - română",
  "Russian - русский язык",
  "Sanskrit (Saṁskṛta) - संस्कृतम्",
  "Sardinian - sardu",
  "Sindhi - सिन्धी, سنڌي، سندھی‎",
  "Northern Sami - Davvisámegiella",
  "Samoan - gagana faa Samoa",
  "Sango - yângâ tî sängö",
  "Serbian - српски језик",
  "Scottish Gaelic; Gaelic - Gàidhlig",
  "Shona - chiShona",
  "Sinhala, Sinhalese - සිංහල",
  "Slovak - slovenčina",
  "Slovene - slovenščina",
  "Somali - Soomaaliga, af Soomaali",
  "Southern Sotho - Sesotho",
  "Spanish; Castilian - español, castellano",
  "Sundanese - Basa Sunda",
  "Swahili - Kiswahili",
  "Swati - SiSwati",
  "Swedish - svenska",
  "Tamil - தமிழ்",
  "Telugu - తెలుగు",
  "Tajik - тоҷикӣ, toğikī, تاجیکی‎",
  "Thai - ไทย",
  "Tigrinya - ትግርኛ",
  "Tibetan Standard, Tibetan, Central - བོད་ཡིག",
  "Turkmen - Türkmen, Түркмен",
  "Tagalog - Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔",
  "Tswana - Setswana",
  "Tonga (Tonga Islands) - faka Tonga",
  "Turkish - Türkçe",
  "Tsonga - Xitsonga",
  "Tatar - татарча, tatarça, تاتارچا‎",
  "Twi - Twi",
  "Tahitian - Reo Tahiti",
  "Uighur, Uyghur - Uyƣurqə, ئۇيغۇرچە‎",
  "Ukrainian - українська",
  "Urdu - اردو",
  "Uzbek - zbek, Ўзбек, أۇزبېك‎",
  "Venda - Tshivenḓa",
  "Vietnamese - Tiếng Việt",
  "Volapük - Volapük",
  "Walloon - Walon",
  "Welsh - Cymraeg",
  "Wolof - Wollof",
  "Western Frisian - Frysk",
  "Xhosa - isiXhosa",
  "Yiddish - ייִדיש",
  "Yoruba - Yorùbá",
  "Zhuang, Chuang - Saɯ cueŋƅ, Saw cuengh",
];
